-- Extend locations table with detailed fields
ALTER TABLE locations ADD COLUMN IF NOT EXISTS address VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS phone VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS location_type VARCHAR(20) NOT NULL DEFAULT '球馆';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();
